---

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-2-release-amd64
  cpu: 8
  memory: 8G
  disk: 40

task:
  matrix:
  - name: aarch64
    env:
      TARGET: aarch64-unknown-freebsd
  - name: armv6
    env:
      TARGET: armv6-unknown-freebsd
  - name: armv7
    env:
      TARGET: armv7-unknown-freebsd
  - name: i686
    env:
      TARGET: i686-unknown-freebsd
  - name: powerpc
    env:
      TARGET: powerpc-unknown-freebsd
  - name: powerpc64
    env:
      TARGET: powerpc64-unknown-freebsd
  - name: powerpc64le
    env:
      TARGET: powerpc64le-unknown-freebsd
  - name: riscv64gc
    env:
      TARGET: riscv64gc-unknown-freebsd
  - name: x86_64
    env:
      TARGET: x86_64-unknown-freebsd
  timeout_in: 120m
  install_script:
    - mkdir -p /usr/local/etc/pkg/repos
    - sed -e 's/quarterly/latest' /etc/pkg/FreeBSD.conf > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg install -y rust-nightly

  build_script:
    - cargo install -Z build-std --verbose --target ${TARGET} ripgrep
