---
name: Build using actions-rust-cross
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: macos-latest
            target: x86_64-unknown-freebsd
            bin: ripgrep
            name: ripgrep-FreeBSD-x86_64.tar.gz
            command: build
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: ripgrep.exe
            name: ripgrep-Windows-x86_64.zip
            command: both
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: ripgrep
            name: ripgrep-Darwin-x86_64.tar.gz
            command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          toolchain: nightly
          args: "--locked --release --verbose"
          strip: true
